export enum EnvKeys {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  HOST = 'HOST',
  API_KEY = 'API_KEY',
  ALLOWED_ORIGINS = 'ALLOWED_ORIGINS',
  LOG_LEVEL = 'LOG_LEVEL',
  DATABASE_URL = 'DATABASE_URL',
  RATE_LIMIT_MAX = 'RATE_LIMIT_MAX',
  RATE_LIMIT_WINDOW = 'RATE_LIMIT_WINDOW',
  MAX_FILE_SIZE = 'MAX_FILE_SIZE',
}
